### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by dubayzac** [dubayzac/MI-449-misc-markdown#1]
## Write a blog article about a computer skill you recently learned

@egillespie Can you take a look at this? It's [hosted here](https://dubayzac.github.io/MI-449-misc-markdown/index.html) and meets the following criteria:

- [x] The skill is learned from a 45-minute or more video, podcast, or event
- [x] All blog content is in one Markdown file containing [at least 400 words](https://wordcounter.net)
- [x] The article uses complete sentences to explain what you learned, but it's okay if the spelling and grammar aren't perfect
- [x] The blog has at least two levels of headings and a link to the video, podcast, or event
- [x] At least five other types of Markdown notation are used that are not headings or links
- [x] The hosted site is generated with a built-in GitHub Pages theme
- [x] The article is viewable at the top level (`/`) of your hosted site

**Comment by egillespie** [comment]
Nice nice, I see lots of Markdown and the page looks good with the minimal theme and images you've selected. 👍 

I don't have any recommendations for improvement. You're all set! 🎉  :shipit:

**Comment by dubayzac** [comment]
Thank you!
